###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka
spring:
  application:
    ####注册中心应用名称
    name: config-server
  cloud:
    config:
      server:
        git:
          ###git环境地址
          uri: https://gitee.com/toov5/distributed_configuration_file.git
          ####目录文件（区分项目的）
          search-paths:
            - Test   
      ####读取分支环境       
      label: master
####服务端口号     
server:
  port: 8888